const constants = {
  INFINITY: 1000000,

  CANVAS_WIDTH: 200,

  CAR_STARTING_POS_X: 100,
  CAR_STARTING_POS_Y: 100,
  CAR_WIDTH: 30,
  CAR_HEIGHT: 50,
  CAR_ACCELERATION: 0.2,
  CAR_MAX_SPEED: 3,
  CAR_FRICTION: 0.05,
  CAR_ANGLE_INCREMENT_FACTOR: 0.03,
  CAR_INITIAL_SPEED: 0,
  CAR_INITIAL_ANGLE: 0.0,

  ROAD_DEFAULT_LANE_COUNT: 3,
  ROAD_LINE_WIDTH: 5,
  ROAD_LINE_COLOR: "white",
  ROAD_MARGINS: 0.96,
  ROAD_DASHED_LINE_GAPS: 20,
  ROAD_DASHED_LINE_LENGTH: 20,
};
