const constants = {
  CANVAS_WIDTH: 200,
  CAR_STARTING_POS_X: 100,
  CAR_STARTING_POS_Y: 100,
  CAR_WIDTH: 30,
  CAR_HEIGHT: 50,
  CAR_ACCELERATION: 0.2,
  CAR_MAX_SPEED: 3,
  CAR_FRICTION: 0.05,
  CAR_ANGLE_INCREMENT_FACTOR: 0.03,
  CAR_INITIAL_SPEED: 0,
  CAR_INITIAL_ANGLE: 0.0,
};
